import Head from 'next/head';
import type { NextPage } from 'next';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>('');
  const router = useRouter();

  return (
    <section id={styles.home_page}>
      <Head>
        <title>Stream Concurrently</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id={styles.bg_colors}>
          <div id={styles.bottom_left}></div>
          <div id={styles.middle_left}></div>
          <div id={styles.middle_right_top}></div>
          <div id={styles.middle_right_bottom}></div>
          <div id={styles.right_top}></div>
          <div id={styles.right_middle}></div>
          <div id={styles.right_middle_top}></div>
        </div>
        <div id={styles.promotion}>let&apos;s watch something &nbsp; <p id={styles.icon}>🎬</p> </div>
        <div id={styles.link_input}>
          <input type="text" autoComplete='off' value={url} onChange={e => setUrl(e.target.value)} id={styles.link} placeholder='Enter. video. link. 🛹' />
          <button id={styles.link_btn} onClick={() => console.log('')} >let&apos;s watch 👻</button>
        </div>
        <div id={styles.credits}>
          <a onClick={() => router.replace('/')} id={styles.logo}>Stream Concurrently&nbsp;<p id={styles.icon}> 🪄 </p></a>
          <p onClick={() => window.open('https://tanishq-singh.herokuapp.com', '_blank')} id={styles.author_name}>MADE BY TANISHQ SINGH 🌠</p>
        </div>
      </main>
    </section>
  );
};

export default Home;